name = "OceanSonar"
uuid = "c288b826-3e30-446a-9364-9aae0e64feb3"
authors = ["Aaron Kaw <aaronjkaw@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
